import type { Curso, Materia, QuestionId, Respostas } from './survey-types'

const materia = (id: string, nome: string, docente: string): Materia => ({
  id,
  nome,
  docente,
})

export const cursos: Curso[] = [
  {
    id: 'administracao',
    nome: 'Administração',
    materias: [
      materia('adm-001', 'Noções Básicas de Administração', 'Profa. Janimayri Forastieri'),
      materia('adm-002', 'Filosofia e Ética', 'Prof. Ricardo Valadão'),
      materia('adm-003', 'Matemática I', 'Profa. Gilza Simão'),
      materia('adm-004', 'Noções Básicas de Engenharia de Produção', 'Prof. Leonardo Brum'),
      materia('adm-005', 'Noções Básicas de Tec. da Informação', 'Prof. Ralph Bini'),
      materia('adm-006', 'Português Instrumental', 'Profa. Maria Eduarda Nogueira'),
      materia('adm-007', 'Estágio Supervisionado I (ADM)', 'Profa. Gisele Muniz'),
      materia('adm-008', 'Estágio Supervisionado II (ADM)', 'Profa. Larissa Tavares'),
      materia('adm-009', 'Trabalho de Conclusão de Curso II - ADM', 'Profa. Janimayri Forastieri'),
      materia('adm-010', 'Matemática II', 'Prof. Vinívius Luz'),
      materia('adm-011', 'Estatística e Probabilidade', 'a definir'),
      materia('adm-012', 'Teoria Geral da Administração', 'Prof. Samuel Martins'),
      materia('adm-013', 'Economia Micro e Macro', 'Profa. Camila Sampaio'),
      materia('adm-014', 'Sociologia', 'a definir'),
      materia('adm-015', 'Inglês Instrumental', 'Prof. Edkleisson de Paiva'),
      materia('adm-016', 'Legislação e Segurança do Trabalho', 'Prof. Antônio Carlos'),
      materia('adm-017', 'Inferência Estatística', 'Profa. Gilza Simão'),
      materia('adm-018', 'Inteligência Emocional', 'Profa. Janimayri Forastieri'),
      materia('adm-019', 'Fundamentos da Contabilidade', 'Profa. Vanessa Aguiar'),
      materia('adm-020', 'Economia Brasileira', 'Profa. Camila Sampaio'),
      materia('adm-021', 'Metodologia de Pesquisa', 'Prof. Alessandro Simão'),
      materia('adm-022', 'Matemática Financeira', 'Profa. Laimara Barroso'),
      materia('adm-023', 'Organização, Sistemas e Métodos', 'Prof. Samuel Martins'),
      materia('adm-024', 'Gestão de Custos', 'a definir'),
      materia('adm-025', 'Arranjo Físico Industrial', 'a definir'),
      materia('adm-026', 'Psicologia Aplicada à Administração', 'Profa. Liliane Cristine'),
      materia('adm-027', 'Raciocínio Lógico', 'Profa. Receba Costa'),
      materia('adm-028', 'Administração Financeira e Orçamentária I', 'a definir'),
      materia('adm-029', 'Marketing I', 'Profa. Janaína Peixoto'),
      materia('adm-030', 'Pesquisa Operacional', 'Profa. Luize Moura'),
      materia('adm-031', 'Direito Público', 'Profa. Fabiana Gomes'),
      materia('adm-032', 'Gestão por Processos', 'a definir'),
      materia('adm-033', 'Gestão de Pessoas', 'Profa. Liliane Cristine'),
      materia('adm-034', 'Marketing II', 'Profa. Janaína Peixoto'),
      materia('adm-035', 'Administração Financeira e Orçamentária II', 'a definir'),
      materia('adm-036', 'Logística', 'Profa. Anírian Cristiane'),
      materia('adm-037', 'Empreendedorismo', 'Profa. Fernanda Falquer'),
      materia('adm-038', 'Direito Privado', 'Profa. Fabiana Gomes'),
      materia('adm-039', 'Gestão Estratégica de Pessoas', 'Profa. Fernanda Falquer'),
      materia('adm-040', 'Gestão da Qualidade', 'Prof. Sérgio Fiuza'),
      materia('adm-041', 'Sistemas de Informações Gerenciais', 'Prof. Emerson Borges'),
      materia('adm-042', 'Gestão Ambiental', 'Profa. Thais Rocha'),
      materia('adm-043', 'Logística e Comércio Exterior', 'Profa. Luize Moura'),
      materia('adm-044', 'Gestão de Materiais e Patrimônio', 'Prof. Ridley Gomes'),
      materia('adm-045', 'Trabalho de Conclusão de Curso I - ADM', 'a definir'),
      materia('adm-046', 'Gestão de Serviços', 'Prof. Samuel Martins'),
      materia('adm-047', 'Gerência de Projetos', 'Prof. Sérgio Fiuza'),
      materia('adm-048', 'Gestão Estratégica', 'Prof. Ridley Gomes'),
      materia('adm-049', 'Simulação de Negócios', 'Profa. Anírian Cristiane'),
      materia('adm-050', 'Integridade Empresarial', 'Profa. Fernanda Falquer'),
      materia('adm-051', 'Administração Pública', 'Profa. Fabiana Gomes'),
    ],
  },
  {
    id: 'engenharia-producao',
    nome: 'Engenharia de Produção',
    materias: [
      materia('ep-001', 'Noções Básicas de Engenharia de Produção', 'Prof. Leonardo Brum'),
      materia('ep-002', 'Noções Básicas de Programação', 'Prof. Sérgio Eduardo'),
      materia('ep-003', 'Introdução ao Cálculo (SI e EP)', 'Profa. Laimara Barroso'),
      materia('ep-004', 'Filosofia e Ética', 'a definir'),
      materia('ep-005', 'Noções Básicas de Administração', 'Prof. Leandro Romitti'),
      materia('ep-006', 'Português Instrumental', 'a definir'),
      materia('ep-007', 'Estágio Supervisionado I (EP)', 'a definir'),
      materia('ep-008', 'Estágio Supervisionado II (EP)', 'Profa. Fabíola Coelho'),
      materia('ep-009', 'Trabalho de Conclusão de Curso II - EP', 'a definir'),
      materia('ep-010', 'Estatística e Probabilidade', 'Profa. Larissa Menezes'),
      materia('ep-011', 'Cálculo Diferencial e Integral I', 'Prof. Vinícius Luz'),
      materia('ep-012', 'Programação de Computadores I', 'Prof. Sérgio Eduardo'),
      materia('ep-013', 'Desenho Técnico', 'Prof. Ridley Gomes'),
      materia('ep-014', 'Fundamentos da Contabilidade', 'Profa. Vanessa Aguiar'),
      materia('ep-015', 'Física I', 'Prof. Nicolas Mota'),
      materia('ep-016', 'Inferência Estatística', 'Profa. Gilza Simão'),
      materia('ep-017', 'Metodologia de Pesquisa', 'a definir'),
      materia('ep-018', 'Física II', 'Prof. Alexandre de Oliveira'),
      materia('ep-019', 'Álgebra Linear', 'Prof. Vinícius Magno'),
      materia('ep-020', 'Cálculo Diferencial e Integral II', 'Prof. Nicolas Mota'),
      materia('ep-021', 'Química Geral', 'Prof. Laercio Lopes'),
      materia('ep-022', 'Física III', 'Prof. Alexandre de Oliveira'),
      materia('ep-023', 'Ciência e Engenharia de Materiais', 'Prof. Antônio Carlos'),
      materia('ep-024', 'Gestão de Custos', 'a definir'),
      materia('ep-025', 'Pesquisa Operacional I', 'Prof. Alessandro Simão'),
      materia('ep-026', 'Cálculo Numérico', 'Prof. Vinícius Magno'),
      materia('ep-027', 'Cálculo Diferencial e Integral III', 'a definir'),
      materia('ep-028', 'Resistência dos Materiais I', 'Profa. Thais Rocha'),
      materia('ep-029', 'Sistemas de Informações Gerenciais', 'Prof. Emerson Borges'),
      materia('ep-030', 'Ergonomia', 'Prof. Leonardo Brum'),
      materia('ep-031', 'Pesquisa Operacional II', 'Prof. Alessandro Simão'),
      materia('ep-032', 'Sistemas Produtivos', 'Prof. Ridley Gomes'),
      materia('ep-033', 'Gestão da Qualida', 'Prof. Sérgio Fiuza'),
      materia('ep-034', 'Resistência dos Materiais II', 'Profa. Thais Rocha'),
      materia('ep-035', 'Processos Industriais e de Fabricação', 'Prof. Felipe Cherchiareto'),
      materia('ep-036', 'Arranjo Físico Industrial', 'a definir'),
      materia('ep-037', 'Fenômenos de Transferências', 'Prof. Rafael Passos'),
      materia('ep-038', 'Logística', 'a definir'),
      materia('ep-039', 'Gestão da Inovação Industrial', 'Prof. Felipe Cherchiareto'),
      materia('ep-040', 'Projeto do Produto', 'Profa. Luize Moura'),
      materia('ep-041', 'Gestão Ambiental', 'Profa. Thais Rocha'),
      materia('ep-042', 'Sistema de Medição', 'Prof. Sérgio Fiuza'),
      materia('ep-043', 'Gestão de Materiais e Patrimônio', 'Prof. Ridley Gomes'),
      materia('ep-044', 'Engenharia Econômica', 'Profa. Camila Sampaio'),
      materia('ep-045', 'Gestão de Cadeia de Abastecimento', 'a definir'),
      materia('ep-046', 'Gerência de Projetos', 'Prof. Sérgio Fiuza'),
      materia('ep-047', 'Gestão Estratégica', 'Prof. Ridley Gomes'),
      materia('ep-048', 'Empreendedorismo', 'Profa. Fernanda Falquer'),
      materia('ep-049', 'Gestão por Processos', 'a definir'),
      materia('ep-050', 'Tecnologias de Gestão da Produção', 'Prof. Ridley Gomes'),
      materia('ep-051', 'Engenharia do Trabalho', 'Prof. Leonardo Brum'),
      materia('ep-052', 'Gestão de Investimento', 'Prof. Antônio Carlos'),
      materia('ep-053', 'Noções Básicas de Engenharia do Petróleo', 'Prof. Laercio Lopes'),
      materia('ep-054', 'Trabalho de Conclusão de Curso I - EP', 'a definir'),
      materia('ep-055', 'Controle Estatístico', 'a definir'),
      materia('ep-056', 'Legislação e Segurança do Trabalho', 'Prof. Antônio Carlos'),
      materia('ep-057', 'Sistemas de Garantia da Qualidade', 'Prof. Felipe Cherchiareto'),
      materia('ep-058', 'Gestão de Manutenção e Confiabilidade', 'Prof. Fábio Ventapane'),
      materia('ep-059', 'Gestão de Pessoas', 'Prof. Janaína Peixoto'),
      materia('ep-060', 'Simulação em Sistemas de Produção', 'a definir'),
      materia('ep-061', 'Tecnologia de Automação e Controle', 'a definir'),
    ],
  },
  {
    id: 'letras',
    nome: 'Licenciatura em Letras',
    materias: [
      materia('let-001', 'Sociologia da Educação', 'Profa. Jéssica Cristina'),
      materia('let-002', 'Políticas de Gestão e Org. da Educação Nacional', 'Profa. Lais de Paula'),
      materia('let-003', 'Literatura Brasileira I', 'Profa. Joice de Lima Pereira'),
      materia('let-004', 'Teoria da Literatura I', 'Prof. Gabriel Guimarães Barbosa'),
      materia('let-005', 'Linguística I', 'Profa. Maria Eduarda Costa'),
      materia('let-006', 'Língua Portuguesa II', 'Profa. Sandra Matsumura'),
      materia('let-007', 'Estágio Curricular Supervisionado I - LETRAS', 'Profa. Claudia Leite'),
      materia('let-008', 'Estágio Curricular Supervisionado II - LETRAS', 'Profa. Claudia Leite'),
    ],
  },
  {
    id: 'matematica',
    nome: 'Licenciatura em Matemática',
    materias: [
      materia('mat-001', 'Filosofia da Educação', 'Prof. Ricardo Valadão'),
      materia('mat-002', 'Leitura e Produção de Textos', 'a definir'),
      materia('mat-003', 'Fundamentos da Matemática Elementar I', 'Profa. Margarete Ramos'),
      materia('mat-004', 'Geometria I', 'Profa. Mariah Rissi'),
      materia('mat-005', 'Matemática Básica I', 'Profa. Aline Viana'),
      materia('mat-006', 'Libras', 'a definir'),
      materia('mat-007', 'Estágio Curricular Supervisionado I (MAT)', 'Profa. Amanda Chaves'),
      materia('mat-008', 'Psicologia da Educação', 'Profa. Joyce Elaine'),
      materia('mat-009', 'Geometria Analítica', 'Profa. Amanda Chaves'),
      materia('mat-010', 'Metodologia de Pesquisa', 'a definir'),
      materia('mat-011', 'Fundamentos da Matemática Elementar III', 'Profa. Margarete Ramos'),
      materia('mat-012', 'Planejamento Educacional e Currículo', 'Profa. Lais de Paula'),
      materia('mat-013', 'Cálculo Diferencial e Integral I', 'a definir'),
      materia('mat-014', 'Inferência Estatística', 'Profa. Gilza Simão'),
      materia('mat-015', 'Álgebra Linear e Geometria Analítica', 'Profa. Isabella Cristina'),
      materia('mat-016', 'Metodologias para o Ensino da Matemática I', 'Profa. Larissa Menezes'),
      materia('mat-017', 'Educação de Jovens e Adultos', 'a definir'),
      materia('mat-018', 'Cálculo Diferencial e Integral III', 'Profa. Rebeca Costa'),
      materia('mat-019', 'Física I', 'Prof. Nicolas Mota'),
      materia('mat-020', 'Estágio Curricular Supervisionado I (MAT)', 'Profa. Joyce Elaine'),
      materia('mat-021', 'Cálculo Diferencial e Integral IV', 'Profa. Amanda Chaves'),
      materia('mat-022', 'Metodologias para o Ensino da Matemática II', 'Profa. Larissa Menezes'),
      materia('mat-023', 'Física II', 'Prof. Alexandre de Oliveira'),
      materia('mat-024', 'Laboratório de Pesquisa em Educ. Matemática I', 'Profa. Aline Viana'),
      materia('mat-025', 'Cálculo Numérico', 'Prof. Vinícius Magno'),
      materia('mat-026', 'Equações Diferenciais e Ordinárias', 'Profa. Aline Viana'),
      materia('mat-027', 'Estágio Curricular Supervisionado II (MAT)', 'Profa. Lais de Paula'),
      materia('mat-028', 'Física III', 'Prof. Alexandre de Oliveira'),
      materia('mat-029', 'Educação Ambiental e Cidadania', 'a definir'),
      materia('mat-030', 'Laboratório de Pesquisa em Educ. Matemática II', 'Profa. Mariah Rissi'),
      materia('mat-031', 'Matemática Computacional', 'Prof. Luciano Rangel'),
      materia('mat-032', 'Matemática Discreta', 'Profa. Margarete Ramos'),
      materia('mat-033', 'Introdução à Álgebra', 'Prof. Vinícius Magno'),
      materia('mat-034', 'Estágio Curricular Supervisionado III (MAT)', 'Profa. Jéssica Cristina'),
      materia('mat-035', 'Trabalho de Conclusão de Curso I - MAT', 'Profa. Joyce Elaine'),
      materia('mat-036', 'Matemática Financeira', 'Profa. Laimara Barroso'),
      materia('mat-037', 'Física IV', 'Prof. Alexandre de Oliveira'),
      materia('mat-038', 'História e Filosofia da Matemática', 'Prof. Vinícius da Cunha'),
      materia('mat-039', 'Análise Real', 'Profa. Isabela Cristina'),
      materia('mat-040', 'Tecnologias no Ensino da Matemática', 'Prof. Luciano Rangel'),
      materia('mat-041', 'Ética, Diversidade e Direitos Humanos', 'a definir'),
      materia('mat-042', 'Estágio Curricular Supervisionado IV - Matemática', 'Profa. Andrea Bottino'),
      materia('mat-043', 'Trabalho de Conclusão de Curso II - MAT', 'Profa. Andrea Bottino'),
    ],
  },
  {
    id: 'pedagogia',
    nome: 'Licenciatura em Pedagogia',
    materias: [
      materia('ped-001', 'Psicologia da Educação', 'Profa. Joyce Elaine'),
      materia('ped-002', 'Sociologia da Educação', 'Profa. Jéssica Cristina'),
      materia('ped-003', 'Didática', 'Profa. Andrea Bottino'),
      materia('ped-004', 'Gestão Democrática e Autonomia', 'a definir'),
      materia('ped-005', 'Políticas de Gestão e Org. da Educação Nacional', 'Profa. Lais de Paula'),
      materia('ped-006', 'Estágio Curricular Supervisionado I -- PED', 'Profa. Bianca Kersbaumer Nogueira'),
      materia('ped-007', 'Estágio Curricular Supervisionado II -- PED', 'Profa. Bianca Kersbaumer Nogueira'),
    ],
  },
  {
    id: 'sistemas-informacao',
    nome: 'Sistemas da Informação',
    materias: [
      materia('si-001', 'Noções Básicas de Programação', 'Prof. Sérgio Eduardo'),
      materia('si-002', 'Filosofia e Ética', 'Prof. Edkleisson de Paiva de Sousa'),
      materia('si-003', 'Noções de Engenharia do Software', 'Prof. Afonso Carlos Tavares'),
      materia('si-004', 'Estruturas Organizacionais', 'Prof. Leonardo Brum'),
      materia('si-005', 'Introdução à Lógica', 'a definir'),
      materia('si-006', 'Português', 'Profa. Maria Eduarda Costa'),
      materia('si-007', 'Estágio Supervisionado I (SI)', 'Profa. Mariah Rissi Leitão'),
      materia('si-008', 'Estágio Supervisionado II (SI)', 'Profa. Valéria Figueiró'),
      materia('si-009', 'Trabalho de Conclusão de Curso II - SI', 'a definir'),
      materia('si-010', 'Cálculo Diferencial e Integral A', 'Profa. Margarete da Silva Ramos'),
      materia('si-011', 'Estatística e Probabilidade', 'Profa. Margarete Ramos'),
      materia('si-012', 'Fundamentos da Contabilidade', 'a definir'),
      materia('si-013', 'Organização de Computadores I', 'Prof. Irineu de Azevedo'),
      materia('si-014', 'Programação de Computadores I', 'Prof. Sérgio Hermenegildo'),
      materia('si-015', 'Análise de Sistemas I', 'Profa. Erica Scheffel'),
      materia('si-016', 'Organização de Computadores II', 'Prof. Ralph Bini'),
      materia('si-017', 'Cálculo Diferencial e Integral B', 'Profa. Laimara da Silva Barroso'),
      materia('si-018', 'Análise de Sistemas II', 'Prof. Emerson Luiz Borges'),
      materia('si-019', 'Inferência Estatística', 'Profa. Rebeca Costa Dias'),
      materia('si-020', 'Metodologia de Pesquisa', 'Profa. Taíse Maria Marchiori'),
      materia('si-021', 'Programação de Computadores II', 'Prof. Sérgio Hermenegildo'),
      materia('si-022', 'Cálculo Numérico (S.I.)', 'Prof. Luciano Rangel'),
      materia('si-023', 'Matemática Discreta', 'Prof. Luciano Rangel'),
      materia('si-024', 'Projeto de Sistemas I', 'Prof. Ralph Bini'),
      materia('si-025', 'Álgebra Linear', 'Prof. Nicolas Mota'),
      materia('si-026', 'Estrutura de Dados I', 'Prof. Irineu de Azevedo'),
      materia('si-027', 'Gerência de Projetos', 'Prof. Afonso Carlos Tavares'),
      materia('si-028', 'Banco de Dados I', 'Prof. Luciano Garcia'),
      materia('si-029', 'Projeto de Sistemas II', 'a definir'),
      materia('si-030', 'Programação de Computadores III', 'a definir'),
      materia('si-031', 'Qualidade de Software', 'Prof. Afonso Carlos Tavares'),
      materia('si-032', 'Pesquisa Operacional I', 'a definir'),
      materia('si-033', 'Estrutura de Dados II', 'Prof. Irineu de Azevedo'),
      materia('si-034', 'Sistemas Operacionais I', 'Prof. Irineu de Azevedo'),
      materia('si-035', 'Inteligência Artificial', 'Prof. Irineu de Azevedo'),
      materia('si-036', 'Banco de Dados II', 'Prof. Luciano Garcia'),
      materia('si-037', 'UX e Desenvolvimento WEB', 'Prof. Sérgio Hermenegildo'),
      materia('si-038', 'Sistemas de Informações Gerenciais', 'Prof. Emerson Borges'),
      materia('si-039', 'Gerência de Sistemas e Projetos', 'Prof. Emerson Borges'),
      materia('si-040', 'Desenvolvimento de Sistemas I', 'Prof. Afonso Carlos Tavares'),
      materia('si-041', 'Sistemas Operacionais II', 'Prof. Ralph Bini'),
      materia('si-042', 'Desenvolvimento para Dispositivos Móveis', 'Prof. Luciano Rangel'),
      materia('si-043', 'Computação em Nuvem', 'Prof. Martinelli de Oliveira'),
      materia('si-044', 'Introdução a Redes de Computadores', 'Profa. Erica Scheffel'),
      materia('si-045', 'Trabalho de Conclusão de Curso I - SI', 'a definir'),
      materia('si-046', 'Banco de Dados III', 'Prof. Luciano Garcia'),
      materia('si-047', 'Gestão de Redes', 'Prof. Irineu de Azevedo'),
      materia('si-048', 'Gerência em Informação', 'Prof. Emerson Borges'),
      materia('si-049', 'Desenvolvimento de Sistemas II', 'Prof. Afonso Carlos Tavares'),
      materia('si-050', 'Empreendedorismo e Gestão Estratégica', 'Prof. Leandro Ulisses Romiti'),
    ],
  },
]

export const escalaAvaliacao = [
  { valor: 1, rotulo: 'Discordo totalmente' },
  { valor: 2, rotulo: 'Discordo' },
  { valor: 3, rotulo: 'Nem concordo nem discordo' },
  { valor: 4, rotulo: 'Concordo' },
  { valor: 5, rotulo: 'Concordo totalmente' },
]

export const textoIntrodutorioAvaliacao =
  'Avalie as afirmações abaixo de acordo com a sua experiência na disciplina. Utilize a escala de 1 a 5, em que 1 significa Discordo totalmente e 5 significa Concordo totalmente. As respostas são confidenciais e utilizadas exclusivamente para fins de avaliação institucional e melhoria acadêmica.'

export const perguntas: Array<{ id: QuestionId; texto: string }> = [
  {
    id: 'q1',
    texto: 'Promove o debate e instiga o pensamento crítico, colaborando para a autonomia dos estudantes.',
  },
  {
    id: 'q2',
    texto: 'Relaciona aspectos teóricos com suas implicações e aplicações práticas.',
  },
  {
    id: 'q3',
    texto: 'Há coerência entre o que é ensinado e o que solicita nas avaliações.',
  },
  {
    id: 'q4',
    texto: 'Utiliza diferentes estratégias avaliativas.',
  },
  {
    id: 'q5',
    texto: 'Relaciona a sua disciplina com conteúdos, competências e habilidades de outras disciplinas do curso.',
  },
  {
    id: 'q6',
    texto: 'Analisa os resultados das avaliações com os estudantes, desenvolvendo mecanismos para a superação das dificuldades.',
  },
  {
    id: 'q7',
    texto: 'Mostra-se aberto ao diálogo, motivando os discentes a prosseguir nos estudos.',
  },
  {
    id: 'q8',
    texto: 'Faz uso adequado do seu tempo regular de aula, facilitando a aprendizagem em sala de aula.',
  },
  {
    id: 'q9',
    texto: 'Apresentou a disciplina disponibilizando plano de curso, estratégias de ensino e critérios de avaliação.',
  },
  {
    id: 'q10',
    texto: 'Utiliza diferentes estratégias pedagógicas ou andragógicas que incentivam a aprendizagem e a pesquisa.',
  },
]

export const defaultRespostas: Respostas = {
  q1: 0,
  q2: 0,
  q3: 0,
  q4: 0,
  q5: 0,
  q6: 0,
  q7: 0,
  q8: 0,
  q9: 0,
  q10: 0,
  comentario: '',
}
